version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password
      MYSQL_DATABASE: eventsProject
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: rihenhouli/events-project:1.0.0
    container_name: events_project
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Empty password if not used
    ports:
      - "8080:8080"

volumes:
  faf161ce77fd246522a2db37e83bb22990140d77ec59abe11b8a4f540bc1adaa:
